[ 2025-01-02 18:49:52,162 ] 49 root - INFO - Setting up MLflow...
[ 2025-01-02 18:49:52,193 ] 58 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-02 18:49:52,193 ] 89 root - INFO - Starting data ingestion...
[ 2025-01-02 18:49:55,662 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-02 18:49:55,664 ] 93 root - INFO - Starting data preprocessing...
[ 2025-01-02 18:49:55,748 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-02 18:49:55,748 ] 97 root - INFO - Starting model training...
[ 2025-01-02 18:49:55,748 ] 74 root - INFO - Starting a new MLflow run...
[ 2025-01-02 18:49:56,395 ] 99 root - INFO - Active MLflow run ID: ddab01b53ac9435ea1bc41eb9f173883
[ 2025-01-02 18:50:00,538 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A9CDCA7040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 18:50:08,809 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A9CDCA7580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 18:50:21,194 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A9CDCA7280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 18:50:44,927 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A9CDCA7850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=ddab01b53ac9435ea1bc41eb9f173883&run_id=ddab01b53ac9435ea1bc41eb9f173883
