[ 2025-01-01 21:18:46,362 ] 48 root - INFO - Setting up MLflow...
[ 2025-01-01 21:18:46,410 ] 57 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-01 21:18:46,410 ] 70 root - INFO - Starting data ingestion...
[ 2025-01-01 21:18:49,597 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-01 21:18:49,599 ] 74 root - INFO - Starting data preprocessing...
[ 2025-01-01 21:18:49,684 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-01 21:18:49,684 ] 78 root - INFO - Starting model training...
[ 2025-01-01 21:18:50,894 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-01 21:18:50,899 ] 29 root - INFO - Missing values handled.
[ 2025-01-01 21:18:50,901 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-01 21:18:50,912 ] 71 root - ERROR - An error occurred during model training: Run with UUID 70eee8b34d6549df90aa50a445309397 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
[ 2025-01-01 21:18:55,060 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397
[ 2025-01-01 21:19:03,378 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E8C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397
[ 2025-01-01 21:19:15,570 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E5C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397
[ 2025-01-01 21:19:36,341 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E6B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397
[ 2025-01-01 21:20:12,833 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E0E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397
[ 2025-01-01 21:20:16,937 ] 88 root - ERROR - An unexpected error occurred: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=70eee8b34d6549df90aa50a445309397&run_id=70eee8b34d6549df90aa50a445309397 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002093361E200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
