[ 2025-01-02 16:09:06,985 ] 49 root - INFO - Setting up MLflow...
[ 2025-01-02 16:09:07,012 ] 58 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-02 16:09:07,013 ] 87 root - INFO - Starting data ingestion...
[ 2025-01-02 16:09:11,432 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-02 16:09:11,434 ] 91 root - INFO - Starting data preprocessing...
[ 2025-01-02 16:09:11,506 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-02 16:09:11,507 ] 95 root - INFO - Starting model training...
[ 2025-01-02 16:09:13,464 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-02 16:09:13,469 ] 29 root - INFO - Missing values handled.
[ 2025-01-02 16:09:13,475 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-02 16:09:13,480 ] 71 root - ERROR - An error occurred during model training: Run with UUID 50725c3d20c34ee8bbe7709eaed1e8c4 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
[ 2025-01-02 16:09:17,599 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D9503760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4
[ 2025-01-02 16:09:25,770 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D95035E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4
[ 2025-01-02 16:09:38,727 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D9503490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4
[ 2025-01-02 16:09:59,735 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D9502C80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4
[ 2025-01-02 16:10:35,948 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D9503070>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4
[ 2025-01-02 16:10:40,060 ] 105 root - ERROR - An unexpected error occurred: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=50725c3d20c34ee8bbe7709eaed1e8c4&run_id=50725c3d20c34ee8bbe7709eaed1e8c4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9D9502470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
