[ 2025-01-01 21:24:39,534 ] 48 root - INFO - Setting up MLflow...
[ 2025-01-01 21:24:39,564 ] 57 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-01 21:24:39,565 ] 70 root - INFO - Starting data ingestion...
[ 2025-01-01 21:24:42,491 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-01 21:24:42,492 ] 74 root - INFO - Starting data preprocessing...
[ 2025-01-01 21:24:42,549 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-01 21:24:42,549 ] 78 root - INFO - Starting model training...
[ 2025-01-01 21:24:43,699 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-01 21:24:43,702 ] 29 root - INFO - Missing values handled.
[ 2025-01-01 21:24:43,706 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-01 21:24:43,715 ] 71 root - ERROR - An error occurred during model training: Run with UUID 15d84bfc09cb4de38cb3d0a053ad6be2 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
[ 2025-01-01 21:24:47,937 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BE1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2
[ 2025-01-01 21:24:56,229 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BE710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2
[ 2025-01-01 21:25:08,998 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BE410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2
[ 2025-01-01 21:25:29,782 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BE500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2
[ 2025-01-01 21:26:06,297 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BDF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2
[ 2025-01-01 21:26:10,430 ] 88 root - ERROR - An unexpected error occurred: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=15d84bfc09cb4de38cb3d0a053ad6be2&run_id=15d84bfc09cb4de38cb3d0a053ad6be2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025FB67BE050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
