[ 2025-01-01 21:22:51,294 ] 48 root - INFO - Setting up MLflow...
[ 2025-01-01 21:22:51,318 ] 57 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-01 21:22:51,318 ] 70 root - INFO - Starting data ingestion...
[ 2025-01-01 21:22:54,417 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-01 21:22:54,418 ] 74 root - INFO - Starting data preprocessing...
[ 2025-01-01 21:22:54,471 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-01 21:22:54,471 ] 78 root - INFO - Starting model training...
[ 2025-01-01 21:22:55,662 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-01 21:22:55,663 ] 29 root - INFO - Missing values handled.
[ 2025-01-01 21:22:55,665 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-01 21:22:55,669 ] 71 root - ERROR - An error occurred during model training: Run with UUID e5c7eb4824ff42edbbbb37398539b6ac is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
[ 2025-01-01 21:22:57,825 ] 88 root - ERROR - An unexpected error occurred: RESOURCE_DOES_NOT_EXIST: Run with id=e5c7eb4824ff42edbbbb37398539b6ac not found
